/**
 * Export curb appeal audit to readable markdown report.
 *
 * Usage: node export.js [data/curb-appeal.jsonl]
 */
import { TimelineExporter } from '../../index.js';

let propertyCount = 0;

const exporter = new TimelineExporter({
  startEvent: 'run_start',
  formatters: {
    run_start(e) {
      return [
        `# Curb Appeal Audit Report`, '',
        `**Neighborhood:** ${e.neighborhood}`,
        `**Properties scanned:** ${e.propertyCount}`, '',
        '---', '',
      ];
    },
    property_start(e) {
      propertyCount++;
      return [
        `## ${propertyCount}. ${e.address}`, '',
        `**Owner:** ${e.owner} | **Est. value:** $${e.homeValue.toLocaleString()}`, '',
      ];
    },
    inspection(e) {
      return [
        `### 🔍 Inspection`, '',
        ...e.content.split('\n').map(l => `> ${l}`), '',
      ];
    },
    estimate(e) {
      return [
        `### 💰 Estimate`, '',
        ...e.content.split('\n').map(l => `> ${l}`), '',
      ];
    },
    outreach(e) {
      return [
        `### ✉️ Outreach`, '',
        e.content, '',
      ];
    },
    qualification(e) {
      return [
        `### 🎯 Lead Score`, '',
        `> ${e.content}`, '',
        '---', '',
      ];
    },
    run_end(e) {
      return [
        `## Summary`, '',
        `**${e.propertyCount} properties** audited in ${e.neighborhood}.`, '',
      ];
    },
  },
  footer: `*Generated by [Chorus](https://github.com/sagaripte/chorus) — multi-agent lead gen pipeline.*`,
});

exporter.run(process.argv[2] || './data/curb-appeal.jsonl');
