/**
 * Export lemonade timeline to readable markdown.
 *
 * Usage: node export.js [data/lemonade.jsonl]
 */
import { TimelineExporter } from '../../index.js';

const dailyRevenue = [];
const WX = { hot: '☀️🔥 Scorching', sunny: '☀️ Sunny', cloudy: '☁️ Overcast', rainy: '🌧️ Rainy' };

const exporter = new TimelineExporter({
  startEvent: 'game_start',
  formatters: {
    game_start(e) {
      return [
        `# Lemonade Stand — Game Transcript`, '',
        `**Kids:** ${e.kids.join(', ')}`,
        `**Goal:** $${e.goal} over ${e.days} days`,
        `**Starting supplies:** ${e.supplies.lemons} lemons, ${e.supplies.sugar} sugar, ${e.supplies.cups} cups`,
        '', '---', '',
      ];
    },
    day_start(e) {
      return [
        `## Day ${e.day} — ${WX[e.weather] || e.weather}`, '',
        `Supplies: ${e.supplies.lemons}🍋 ${e.supplies.sugar}🍚 ${e.supplies.cups}🥤 | Revenue so far: $${e.totalRevenue.toFixed(2)}`, '',
      ];
    },
    debate(e) { return [`**${e.from}:** ${e.content}`, '']; },
    vote(e) { return [`> **${e.kid}** votes: $${e.price} at ${e.location}`, '']; },
    sales(e) {
      dailyRevenue.push({ day: e.day, revenue: e.revenue, total: e.totalRevenue, sold: e.sold });
      const lines = [
        '---', '',
        `**Decision:** $${e.price} at ${e.location}`, '',
        `| | |`, `|---|---|`,
        `| **Sold** | ${e.sold} cups |`,
        `| **Revenue** | $${e.revenue.toFixed(2)} |`,
        `| **Demand** | ${e.demand} people |`,
      ];
      if (e.unfulfilled > 0) lines.push(`| **Turned away** | ${e.unfulfilled} people |`);
      lines.push(`| **Running total** | $${e.totalRevenue.toFixed(2)} / $100 |`, '');
      return lines;
    },
    reaction(e) { return [`**${e.from}:** ${e.content}`, '']; },
    out_of_supplies() { return [`**Out of supplies! Season over.**`, '']; },
    game_end(e) {
      const lines = [
        '---', '',
        `## Final Results`, '',
        e.hit ? `**🎉 GOAL REACHED!**` : `**😔 Fell short.**`, '',
        `| | |`, `|---|---|`,
        `| **Total revenue** | $${e.totalRevenue.toFixed(2)} |`,
        `| **Goal** | $${e.goal} |`,
        `| **Supplies left** | ${e.supplies.lemons}🍋 ${e.supplies.sugar}🍚 ${e.supplies.cups}🥤 |`, '',
      ];
      // Append revenue chart
      if (dailyRevenue.length > 0) {
        lines.push('---', '', '## Daily Revenue', '',
          '| Day | Sold | Revenue | Running Total |',
          '|-----|------|---------|---------------|');
        for (const d of dailyRevenue) {
          const bar = '█'.repeat(Math.round(d.revenue / 5));
          lines.push(`| ${d.day} | ${d.sold} cups | $${d.revenue.toFixed(2)} ${bar} | $${d.total.toFixed(2)} |`);
        }
        lines.push('');
      }
      return lines;
    },
    reflection(e) { return [`**${e.from}:** ${e.content}`, '']; },
  },
  footer: `*Generated by [Chorus](https://github.com/sagaripte/chorus)*`,
});

exporter.run(process.argv[2] || './data/lemonade.jsonl');
