/**
 * Export lemonade timeline to readable markdown.
 *
 * Usage: node export.js [data/lemonade.jsonl]
 */
import { readFileSync, writeFileSync } from 'fs';

const input = process.argv[2] || './data/lemonade.jsonl';
const output = input.replace('.jsonl', '.md');

let events = readFileSync(input, 'utf8')
  .trim().split('\n').filter(Boolean)
  .map(line => { try { return JSON.parse(line); } catch { return null; } })
  .filter(Boolean);

const lastStart = events.findLastIndex(e => e.type === 'game_start');
if (lastStart > 0) events = events.slice(lastStart);

const lines = [];
const push = (s = '') => lines.push(s);

const dailyRevenue = [];

for (const e of events) {
  switch (e.type) {
    case 'game_start':
      push(`# Lemonade Stand — Game Transcript`);
      push();
      push(`**Kids:** ${e.kids.join(', ')}`);
      push(`**Goal:** $${e.goal} over ${e.days} days`);
      push(`**Starting supplies:** ${e.supplies.lemons} lemons, ${e.supplies.sugar} sugar, ${e.supplies.cups} cups`);
      push();
      push('---');
      push();
      break;

    case 'day_start': {
      const wx = { hot: '☀️🔥 Scorching', sunny: '☀️ Sunny', cloudy: '☁️ Overcast', rainy: '🌧️ Rainy' };
      push(`## Day ${e.day} — ${wx[e.weather] || e.weather}`);
      push();
      push(`Supplies: ${e.supplies.lemons}🍋 ${e.supplies.sugar}🍚 ${e.supplies.cups}🥤 | Revenue so far: $${e.totalRevenue.toFixed(2)}`);
      push();
      break;
    }

    case 'debate':
      push(`**${e.from}:** ${e.content}`);
      push();
      break;

    case 'vote':
      push(`> **${e.kid}** votes: $${e.price} at ${e.location}`);
      push();
      break;

    case 'sales': {
      push('---');
      push();
      push(`**Decision:** $${e.price} at ${e.location}`);
      push();
      push(`| | |`);
      push(`|---|---|`);
      push(`| **Sold** | ${e.sold} cups |`);
      push(`| **Revenue** | $${e.revenue.toFixed(2)} |`);
      push(`| **Demand** | ${e.demand} people |`);
      if (e.unfulfilled > 0) push(`| **Turned away** | ${e.unfulfilled} people |`);
      push(`| **Running total** | $${e.totalRevenue.toFixed(2)} / $100 |`);
      push();
      dailyRevenue.push({ day: e.day, revenue: e.revenue, total: e.totalRevenue, sold: e.sold });
      break;
    }

    case 'reaction':
      push(`**${e.from}:** ${e.content}`);
      push();
      break;

    case 'out_of_supplies':
      push(`**Out of supplies! Season over.**`);
      push();
      break;

    case 'game_end': {
      push('---');
      push();
      push(`## Final Results`);
      push();
      push(e.hit ? `**🎉 GOAL REACHED!**` : `**😔 Fell short.**`);
      push();
      push(`| | |`);
      push(`|---|---|`);
      push(`| **Total revenue** | $${e.totalRevenue.toFixed(2)} |`);
      push(`| **Goal** | $${e.goal} |`);
      push(`| **Supplies left** | ${e.supplies.lemons}🍋 ${e.supplies.sugar}🍚 ${e.supplies.cups}🥤 |`);
      push();
      break;
    }

    case 'reflection':
      push(`**${e.from}:** ${e.content}`);
      push();
      break;
  }
}

// Revenue chart
if (dailyRevenue.length > 0) {
  push('---');
  push();
  push('## Daily Revenue');
  push();
  push('| Day | Sold | Revenue | Running Total |');
  push('|-----|------|---------|---------------|');
  for (const d of dailyRevenue) {
    const bar = '█'.repeat(Math.round(d.revenue / 5));
    push(`| ${d.day} | ${d.sold} cups | $${d.revenue.toFixed(2)} ${bar} | $${d.total.toFixed(2)} |`);
  }
  push();
}

push('---');
push();
push(`*Generated by [Chorus](https://github.com/anthropics/chorus)*`);

writeFileSync(output, lines.join('\n'));
console.log(`Exported to ${output}`);
